// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDClMc42TrdCB_1V8GkmVLRLegDwizHI7s',
    appId: '1:269474518191:web:35e7790cea90df4af5f05a',
    messagingSenderId: '269474518191',
    projectId: 'triple-m-1bda1',
    authDomain: 'triple-m-1bda1.firebaseapp.com',
    storageBucket: 'triple-m-1bda1.firebasestorage.app',
    measurementId: 'G-Z0J88CHMSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdl5dZcH-riA_gBFUVc2Yw0ZA39IzG-ck',
    appId: '1:269474518191:android:671340a53678c1e2f5f05a',
    messagingSenderId: '269474518191',
    projectId: 'triple-m-1bda1',
    storageBucket: 'triple-m-1bda1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKxBtch2OvHM-JgQyqbZrCgqCCUsGL9g',
    appId: '1:269474518191:ios:e536b919757be97cf5f05a',
    messagingSenderId: '269474518191',
    projectId: 'triple-m-1bda1',
    storageBucket: 'triple-m-1bda1.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxKxBtch2OvHM-JgQyqbZrCgqCCUsGL9g',
    appId: '1:269474518191:ios:e536b919757be97cf5f05a',
    messagingSenderId: '269474518191',
    projectId: 'triple-m-1bda1',
    storageBucket: 'triple-m-1bda1.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDClMc42TrdCB_1V8GkmVLRLegDwizHI7s',
    appId: '1:269474518191:web:33ff627834f2069bf5f05a',
    messagingSenderId: '269474518191',
    projectId: 'triple-m-1bda1',
    authDomain: 'triple-m-1bda1.firebaseapp.com',
    storageBucket: 'triple-m-1bda1.firebasestorage.app',
    measurementId: 'G-LSYNYCXNH7',
  );
}
