// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static final FirebaseOptions web = FirebaseOptions(
      apiKey: _requiredValue(
        const String.fromEnvironment(_webApiKeyName),
        _webApiKeyName,
      ),
      appId: _requiredValue(
        const String.fromEnvironment(_webAppIdName),
        _webAppIdName,
      ),
      messagingSenderId: _requiredValue(
        const String.fromEnvironment(_webMessagingSenderIdName),
        _webMessagingSenderIdName,
      ),
      projectId: _requiredValue(
        const String.fromEnvironment(_webProjectIdName),
        _webProjectIdName,
      ),
      authDomain: _requiredValue(
        const String.fromEnvironment(_webAuthDomainName),
        _webAuthDomainName,
      ),
      storageBucket: _requiredValue(
        const String.fromEnvironment(_webStorageBucketName),
        _webStorageBucketName,
      ),
      measurementId: _requiredValue(
        const String.fromEnvironment(_webMeasurementIdName),
        _webMeasurementIdName,
      ),
    );

    static final FirebaseOptions android = FirebaseOptions(
      apiKey: _requiredValue(
        const String.fromEnvironment(_androidApiKeyName),
        _androidApiKeyName,
      ),
      appId: _requiredValue(
        const String.fromEnvironment(_androidAppIdName),
        _androidAppIdName,
      ),
      messagingSenderId: _requiredValue(
        const String.fromEnvironment(_androidMessagingSenderIdName),
        _androidMessagingSenderIdName,
      ),
      projectId: _requiredValue(
        const String.fromEnvironment(_androidProjectIdName),
        _androidProjectIdName,
      ),
      storageBucket: _requiredValue(
        const String.fromEnvironment(_androidStorageBucketName),
        _androidStorageBucketName,
      ),
    );

    static final FirebaseOptions ios = FirebaseOptions(
      apiKey: _requiredValue(
        const String.fromEnvironment(_iosApiKeyName),
        _iosApiKeyName,
      ),
      appId: _requiredValue(
        const String.fromEnvironment(_iosAppIdName),
        _iosAppIdName,
      ),
      messagingSenderId: _requiredValue(
        const String.fromEnvironment(_iosMessagingSenderIdName),
        _iosMessagingSenderIdName,
      ),
      projectId: _requiredValue(
        const String.fromEnvironment(_iosProjectIdName),
        _iosProjectIdName,
      ),
      storageBucket: _requiredValue(
        const String.fromEnvironment(_iosStorageBucketName),
        _iosStorageBucketName,
      ),
      iosBundleId: _requiredValue(
        const String.fromEnvironment(_iosBundleIdName),
        _iosBundleIdName,
      ),
    );

    static final FirebaseOptions macos = FirebaseOptions(
      apiKey: _requiredValue(
        const String.fromEnvironment(_macosApiKeyName),
        _macosApiKeyName,
      ),
      appId: _requiredValue(
        const String.fromEnvironment(_macosAppIdName),
        _macosAppIdName,
      ),
      messagingSenderId: _requiredValue(
        const String.fromEnvironment(_macosMessagingSenderIdName),
        _macosMessagingSenderIdName,
      ),
      projectId: _requiredValue(
        const String.fromEnvironment(_macosProjectIdName),
        _macosProjectIdName,
      ),
      storageBucket: _requiredValue(
        const String.fromEnvironment(_macosStorageBucketName),
        _macosStorageBucketName,
      ),
      iosBundleId: _requiredValue(
        const String.fromEnvironment(_macosBundleIdName),
        _macosBundleIdName,
      ),
    );

    static final FirebaseOptions windows = FirebaseOptions(
      apiKey: _requiredValue(
        const String.fromEnvironment(_windowsApiKeyName),
        _windowsApiKeyName,
      ),
      appId: _requiredValue(
        const String.fromEnvironment(_windowsAppIdName),
        _windowsAppIdName,
      ),
      messagingSenderId: _requiredValue(
        const String.fromEnvironment(_windowsMessagingSenderIdName),
        _windowsMessagingSenderIdName,
      ),
      projectId: _requiredValue(
        const String.fromEnvironment(_windowsProjectIdName),
        _windowsProjectIdName,
      ),
      authDomain: _requiredValue(
        const String.fromEnvironment(_windowsAuthDomainName),
        _windowsAuthDomainName,
      ),
      storageBucket: _requiredValue(
        const String.fromEnvironment(_windowsStorageBucketName),
        _windowsStorageBucketName,
      ),
      measurementId: _requiredValue(
        const String.fromEnvironment(_windowsMeasurementIdName),
        _windowsMeasurementIdName,
      ),
    );

    static const String _webApiKeyName = 'FIREBASE_WEB_API_KEY';
    static const String _webAppIdName = 'FIREBASE_WEB_APP_ID';
    static const String _webMessagingSenderIdName =
        'FIREBASE_WEB_MESSAGING_SENDER_ID';
    static const String _webProjectIdName = 'FIREBASE_WEB_PROJECT_ID';
    static const String _webAuthDomainName = 'FIREBASE_WEB_AUTH_DOMAIN';
    static const String _webStorageBucketName = 'FIREBASE_WEB_STORAGE_BUCKET';
    static const String _webMeasurementIdName = 'FIREBASE_WEB_MEASUREMENT_ID';

    static const String _androidApiKeyName = 'FIREBASE_ANDROID_API_KEY';
    static const String _androidAppIdName = 'FIREBASE_ANDROID_APP_ID';
    static const String _androidMessagingSenderIdName =
        'FIREBASE_ANDROID_MESSAGING_SENDER_ID';
    static const String _androidProjectIdName = 'FIREBASE_ANDROID_PROJECT_ID';
    static const String _androidStorageBucketName =
        'FIREBASE_ANDROID_STORAGE_BUCKET';

    static const String _iosApiKeyName = 'FIREBASE_IOS_API_KEY';
    static const String _iosAppIdName = 'FIREBASE_IOS_APP_ID';
    static const String _iosMessagingSenderIdName =
        'FIREBASE_IOS_MESSAGING_SENDER_ID';
    static const String _iosProjectIdName = 'FIREBASE_IOS_PROJECT_ID';
    static const String _iosStorageBucketName = 'FIREBASE_IOS_STORAGE_BUCKET';
    static const String _iosBundleIdName = 'FIREBASE_IOS_BUNDLE_ID';

    static const String _macosApiKeyName = 'FIREBASE_IOS_API_KEY';
    static const String _macosAppIdName = 'FIREBASE_IOS_APP_ID';
    static const String _macosMessagingSenderIdName =
        'FIREBASE_IOS_MESSAGING_SENDER_ID';
    static const String _macosProjectIdName = 'FIREBASE_IOS_PROJECT_ID';
    static const String _macosStorageBucketName = 'FIREBASE_IOS_STORAGE_BUCKET';
    static const String _macosBundleIdName = 'FIREBASE_IOS_BUNDLE_ID';

    static const String _windowsApiKeyName = 'FIREBASE_WINDOWS_API_KEY';
    static const String _windowsAppIdName = 'FIREBASE_WINDOWS_APP_ID';
    static const String _windowsMessagingSenderIdName =
        'FIREBASE_WINDOWS_MESSAGING_SENDER_ID';
    static const String _windowsProjectIdName = 'FIREBASE_WINDOWS_PROJECT_ID';
    static const String _windowsAuthDomainName = 'FIREBASE_WINDOWS_AUTH_DOMAIN';
    static const String _windowsStorageBucketName =
        'FIREBASE_WINDOWS_STORAGE_BUCKET';
    static const String _windowsMeasurementIdName =
        'FIREBASE_WINDOWS_MEASUREMENT_ID';

    static String _requiredValue(String value, String keyName) {
      if (value.isEmpty) {
        throw StateError(
          'Missing Firebase config value for $keyName. Copy .env.example to .env '
          'and build with --dart-define-from-file=.env.',
        );
      }
      return value;
    }
}
